### ISSUE TITLE
System.TypeLoadException Error

### ISSUE THREAD

**Issue by vasim07** [action-bi-toolkit/adventureworksdw2020-pbix#1]
On my windows machine, the below code produces the following error.

`pbi-tools compile-pbix -folder ./pbix -format PBIT -outPath AdvWorksDW2020.pbit`

![image](https://user-images.githubusercontent.com/7251222/137129482-8f1994b3-6b30-4546-ad01-c4f32c95825a.png)

On version 1.0.0-beta5.

Just as info, the latest version is detected as virus - not sure why is this the case though.

**Comment by mthierba** [comment]
Windows "blocks" certain downloaded files  from being executed by default. This site had good instructions how to handle those: https://singularlabs.com/tips/how-to-unblock-a-zip-file-on-windows-10/ This is not a hack, standard Windows procedure.
